id24_FrequencyOfArrayElements
ihccik/EvergrovingTaskRepo pull request #22
Opened 2022-08-11 17:30 UTC by ihccik

assumptions added
example explanation added
map and stream solution added
sheet updated
file name changed
task name updated with more meaningful one

2022-08-13 09:43 UTC, Cemil5 commented on src/array/id24_FrequencyOfArrayElements.java
> +
hash map solution can be added :
static Map<String, Integer> solutionWithMap(String[] testArray){
Map<String, Integer> map = new HashMap<>();
for (String str : testArray) {
map.put(str, map.getOrDefault(str, 0)+1);
}
return map;
}

2022-08-13 09:44 UTC, Cemil5 requested changes
hash map solution can be added :
static Map<String, Integer> solutionWithMap(String[] testArray){
Map<String, Integer> map = new HashMap<>();
for (String str : testArray) {
map.put(str, map.getOrDefault(str, 0)+1);
}
return map;
}

2022-08-14 09:41 UTC, ihccik commented on src/array/id24_FrequencyOfArrayElements.java
> +
@Cemil5 requested changes reflected

2022-08-14 14:14 UTC, Cemil5 approved these changes

2022-08-14 14:15 UTC, merged